config/routes.rb
Rails.application.routes.draw do
  resources :certification_authorities
  resources :cities
  resources :states
  resources :cert_authority_types
  resources :ranking_authorities
  resources :institution_types
  resources :course_types
  resources :course_levels
  resources :streams
  root 'dashboard#index'

  resources :study_modes

end

app/models/certification_authority.rb
class CertificationAuthority < ActiveRecord::Base
  belongs_to :cert_authority_type
  belongs_to :city
end

app/controllers/certification_authorities_controller.rb
class CertificationAuthoritiesController < ApplicationController
  before_action :set_certification_authority, only: [:show, :edit, :update, :destroy]

  # GET /certification_authorities
  # GET /certification_authorities.json
  def index
    @certification_authorities = CertificationAuthority.all
  end

  # GET /certification_authorities/1
  # GET /certification_authorities/1.json
  def show
  end

  # GET /certification_authorities/new
  def new
    @certification_authority = CertificationAuthority.new
  end

  # GET /certification_authorities/1/edit
  def edit
  end

  # POST /certification_authorities
  # POST /certification_authorities.json
  def create
    @certification_authority = CertificationAuthority.new(certification_authority_params)

    respond_to do |format|
      if @certification_authority.save
        format.html { redirect_to @certification_authority, notice: 'Certification authority was successfully created.' }
        format.json { render :show, status: :created, location: @certification_authority }
      else
        format.html { render :new }
        format.json { render json: @certification_authority.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /certification_authorities/1
  # PATCH/PUT /certification_authorities/1.json
  def update
    respond_to do |format|
      if @certification_authority.update(certification_authority_params)
        format.html { redirect_to @certification_authority, notice: 'Certification authority was successfully updated.' }
        format.json { render :show, status: :ok, location: @certification_authority }
      else
        format.html { render :edit }
        format.json { render json: @certification_authority.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /certification_authorities/1
  # DELETE /certification_authorities/1.json
  def destroy
    @certification_authority.destroy
    respond_to do |format|
      format.html { redirect_to certification_authorities_url, notice: 'Certification authority was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_certification_authority
      @certification_authority = CertificationAuthority.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def certification_authority_params
      params.require(:certification_authority).permit(:name, :code, :cert_authority_type_id, :city_id)
    end
end

app/helpers/certification_authorities_helper.rb
module CertificationAuthoritiesHelper
end

app/views/certification_authorities/_form.html.erb
<%= form_for(@certification_authority) do |f| %>
  <% if @certification_authority.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@certification_authority.errors.count, "error") %> prohibited this certification_authority from being saved:</h2>

      <ul>
      <% @certification_authority.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :code %><br>
    <%= f.text_field :code %>
  </div>
  <div class="field">
    <%= f.label :cert_authority_type_id %><br>
    <%= f.text_field :cert_authority_type_id %>
  </div>
  <div class="field">
    <%= f.label :city_id %><br>
    <%= f.text_field :city_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/certification_authorities/edit.html.erb
<h1>Editing Certification Authority</h1>

<%= render 'form' %>

<%= link_to 'Show', @certification_authority %> |
<%= link_to 'Back', certification_authorities_path %>

app/views/certification_authorities/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Certification Authorities</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Code</th>
      <th>Cert authority type</th>
      <th>City</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @certification_authorities.each do |certification_authority| %>
      <tr>
        <td><%= certification_authority.name %></td>
        <td><%= certification_authority.code %></td>
        <td><%= certification_authority.cert_authority_type %></td>
        <td><%= certification_authority.city %></td>
        <td><%= link_to 'Show', certification_authority %></td>
        <td><%= link_to 'Edit', edit_certification_authority_path(certification_authority) %></td>
        <td><%= link_to 'Destroy', certification_authority, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Certification authority', new_certification_authority_path %>

app/views/certification_authorities/new.html.erb
<h1>New Certification Authority</h1>

<%= render 'form' %>

<%= link_to 'Back', certification_authorities_path %>

app/views/certification_authorities/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @certification_authority.name %>
</p>

<p>
  <strong>Code:</strong>
  <%= @certification_authority.code %>
</p>

<p>
  <strong>Cert authority type:</strong>
  <%= @certification_authority.cert_authority_type %>
</p>

<p>
  <strong>City:</strong>
  <%= @certification_authority.city %>
</p>

<%= link_to 'Edit', edit_certification_authority_path(@certification_authority) %> |
<%= link_to 'Back', certification_authorities_path %>