config/routes.rb
Rails.application.routes.draw do
  resources :certification_authorities
  resources :cities
  resources :states
  resources :cert_authority_types
  resources :ranking_authorities
  resources :institution_types
  resources :course_types
  resources :course_levels
  resources :streams
  root 'dashboard#index'

  resources :study_modes

end

app/models/study_mode.rb
class StudyMode < ActiveRecord::Base
end

app/controllers/study_modes_controller.rb
class StudyModesController < ApplicationController
  before_action :set_study_mode, only: [:show, :edit, :update, :destroy]

  # GET /study_modes
  # GET /study_modes.json
  def index
    @study_modes = StudyMode.all
  end

  # GET /study_modes/1
  # GET /study_modes/1.json
  def show
  end

  # GET /study_modes/new
  def new
    @study_mode = StudyMode.new
  end

  # GET /study_modes/1/edit
  def edit
  end

  # POST /study_modes
  # POST /study_modes.json
  def create
    @study_mode = StudyMode.new(study_mode_params)

    respond_to do |format|
      if @study_mode.save
        format.html { redirect_to @study_mode, notice: 'Study mode was successfully created.' }
        format.json { render :show, status: :created, location: @study_mode }
      else
        format.html { render :new }
        format.json { render json: @study_mode.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /study_modes/1
  # PATCH/PUT /study_modes/1.json
  def update
    respond_to do |format|
      if @study_mode.update(study_mode_params)
        format.html { redirect_to @study_mode, notice: 'Study mode was successfully updated.' }
        format.json { render :show, status: :ok, location: @study_mode }
      else
        format.html { render :edit }
        format.json { render json: @study_mode.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /study_modes/1
  # DELETE /study_modes/1.json
  def destroy
    @study_mode.destroy
    respond_to do |format|
      format.html { redirect_to study_modes_url, notice: 'Study mode was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_study_mode
      @study_mode = StudyMode.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def study_mode_params
      params.require(:study_mode).permit(:name)
    end
end

app/helpers/study_modes_helper.rb
module StudyModesHelper
end

app/views/study_modes/_form.html.erb
<%= form_for(@study_mode) do |f| %>
  <% if @study_mode.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@study_mode.errors.count, "error") %> prohibited this study_mode from being saved:</h2>

      <ul>
      <% @study_mode.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/study_modes/edit.html.erb
<h1>Editing Study Mode</h1>

<%= render 'form' %>

<%= link_to 'Show', @study_mode %> |
<%= link_to 'Back', study_modes_path %>

app/views/study_modes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Study Modes</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @study_modes.each do |study_mode| %>
      <tr>
        <td><%= study_mode.name %></td>
        <td><%= link_to 'Show', study_mode %></td>
        <td><%= link_to 'Edit', edit_study_mode_path(study_mode) %></td>
        <td><%= link_to 'Destroy', study_mode, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Study mode', new_study_mode_path %>

app/views/study_modes/new.html.erb
<h1>New Study Mode</h1>

<%= render 'form' %>

<%= link_to 'Back', study_modes_path %>

app/views/study_modes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @study_mode.name %>
</p>

<%= link_to 'Edit', edit_study_mode_path(@study_mode) %> |
<%= link_to 'Back', study_modes_path %>