config/routes.rb
Rails.application.routes.draw do
  resources :certification_authorities
  resources :cities
  resources :states
  resources :cert_authority_types
  resources :ranking_authorities
  resources :institution_types
  resources :course_types
  resources :course_levels
  resources :streams
  root 'dashboard#index'

  resources :study_modes

end

app/controllers/cert_authority_types_controller.rb
class CertAuthorityTypesController < ApplicationController
  before_action :set_cert_authority_type, only: [:show, :edit, :update, :destroy]

  # GET /cert_authority_types
  # GET /cert_authority_types.json
  def index
    @cert_authority_types = CertAuthorityType.all
  end

  # GET /cert_authority_types/1
  # GET /cert_authority_types/1.json
  def show
  end

  # GET /cert_authority_types/new
  def new
    @cert_authority_type = CertAuthorityType.new
  end

  # GET /cert_authority_types/1/edit
  def edit
  end

  # POST /cert_authority_types
  # POST /cert_authority_types.json
  def create
    @cert_authority_type = CertAuthorityType.new(cert_authority_type_params)

    respond_to do |format|
      if @cert_authority_type.save
        format.html { redirect_to @cert_authority_type, notice: 'Cert authority type was successfully created.' }
        format.json { render :show, status: :created, location: @cert_authority_type }
      else
        format.html { render :new }
        format.json { render json: @cert_authority_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cert_authority_types/1
  # PATCH/PUT /cert_authority_types/1.json
  def update
    respond_to do |format|
      if @cert_authority_type.update(cert_authority_type_params)
        format.html { redirect_to @cert_authority_type, notice: 'Cert authority type was successfully updated.' }
        format.json { render :show, status: :ok, location: @cert_authority_type }
      else
        format.html { render :edit }
        format.json { render json: @cert_authority_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cert_authority_types/1
  # DELETE /cert_authority_types/1.json
  def destroy
    @cert_authority_type.destroy
    respond_to do |format|
      format.html { redirect_to cert_authority_types_url, notice: 'Cert authority type was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cert_authority_type
      @cert_authority_type = CertAuthorityType.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cert_authority_type_params
      params.require(:cert_authority_type).permit(:name)
    end
end

app/helpers/cert_authority_types_helper.rb
module CertAuthorityTypesHelper
end

app/views/cert_authority_types/_form.html.erb
<%= form_for(@cert_authority_type) do |f| %>
  <% if @cert_authority_type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cert_authority_type.errors.count, "error") %> prohibited this cert_authority_type from being saved:</h2>

      <ul>
      <% @cert_authority_type.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/cert_authority_types/edit.html.erb
<h1>Editing Cert Authority Type</h1>

<%= render 'form' %>

<%= link_to 'Show', @cert_authority_type %> |
<%= link_to 'Back', cert_authority_types_path %>

app/views/cert_authority_types/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Cert Authority Types</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cert_authority_types.each do |cert_authority_type| %>
      <tr>
        <td><%= cert_authority_type.name %></td>
        <td><%= link_to 'Show', cert_authority_type %></td>
        <td><%= link_to 'Edit', edit_cert_authority_type_path(cert_authority_type) %></td>
        <td><%= link_to 'Destroy', cert_authority_type, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cert authority type', new_cert_authority_type_path %>

app/views/cert_authority_types/new.html.erb
<h1>New Cert Authority Type</h1>

<%= render 'form' %>

<%= link_to 'Back', cert_authority_types_path %>

app/views/cert_authority_types/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @cert_authority_type.name %>
</p>

<%= link_to 'Edit', edit_cert_authority_type_path(@cert_authority_type) %> |
<%= link_to 'Back', cert_authority_types_path %>